### ISSUE TITLE
Incorrect returned value from GetTraceBackFlow

### ISSUE THREAD

**Issue by davidleesbir3** [KztTateyama/supply-chain-app#13]
In some cases, GetTraceBackFlow returns more items than expected. Assuming the following case:

Please see  [**screenshot1**](https://www.notion.so/Screenshots-15f7a67979774c299a836f831afc4468)

If I run GetTraceBackFlow on **PartyC** for `20210517-car-0001`, it returns the correct results. 

However, if I call GetTraceBackFlow for `20210517-car-0002`, it returns the following:  

```bash
"result": {
        "lotID": "20210517-car-0002",
        "trace": [
            {
                "item": "car",
                "lotID": "20210517-car-0001",
                "manufacturer": "O=PartyC, L=New York, C=US",
                "manufacturedDate": "2021-05-17T17:58:30.377"
            },
            {
                "item": "tire",
                "lotID": "20210517-tire-0001",
                "manufacturer": "O=PartyB, L=New York, C=US",
                "manufacturedDate": "2021-05-17T17:57:26.910"
            },
            {
                "item": "rubber",
                "lotID": "20210517-rubber-0001",
                "manufacturer": "O=PartyA, L=London, C=GB",
                "manufacturedDate": "2021-05-17T17:56:21.253"
            },
            {
                "item": "wire",
                "lotID": "20210517-wire-0001",
                "manufacturer": "O=PartyA, L=London, C=GB",
                "manufacturedDate": "2021-05-17T17:56:26.629"
            }
        ]
    }
```

Also, on **PartyC** if I run GetTraceBackFlow for `20210517-tire-0001`, it returns the following:

```bash
"result": {
        "lotID": "20210517-tire-0001",
        "trace": [
            {
                "item": "car",
                "lotID": "20210517-car-0001",
                "manufacturer": "O=PartyC, L=New York, C=US",
                "manufacturedDate": "2021-05-17T17:58:30.377"
            },
            {
                "item": "tire",
                "lotID": "20210517-tire-0001",
                "manufacturer": "O=PartyB, L=New York, C=US",
                "manufacturedDate": "2021-05-17T17:57:26.910"
            },
            {
                "item": "rubber",
                "lotID": "20210517-rubber-0001",
                "manufacturer": "O=PartyA, L=London, C=GB",
                "manufacturedDate": "2021-05-17T17:56:21.253"
            },
            {
                "item": "wire",
                "lotID": "20210517-wire-0001",
                "manufacturer": "O=PartyA, L=London, C=GB",
                "manufacturedDate": "2021-05-17T17:56:26.629"
            }
        ]
    }
```

Similar problem was noticed if I call it for `20210517-tire-0001` on **PartyB**, in which case I got the following

```bash
"result": {
        "lotID": "20210517-tire-0001",
        "trace": [
            {
                "item": "tire",
                "lotID": "20210517-tire-0001",
                "manufacturer": "O=PartyB, L=New York, C=US",
                "manufacturedDate": "2021-05-17T17:57:26.910"
            },
            {
                "item": "rubber",
                "lotID": "20210517-rubber-0001",
                "manufacturer": "O=PartyA, L=London, C=GB",
                "manufacturedDate": "2021-05-17T17:56:21.253"
            },
            {
                "item": "wire",
                "lotID": "20210517-wire-0001",
                "manufacturer": "O=PartyA, L=London, C=GB",
                "manufacturedDate": "2021-05-17T17:56:26.629"
            }
        ]
    }
```

**Comment by KztTateyama** [comment]
This was due to an omission of consideration when filtering the output State of the traced Transaction.Since each product is fungible, it is assumed that part of the State will be consumed in the manufacture of one product and then consumed in another chain. In this case, the manufactured state (in the above example, "Tire") is also part of the Output State of the Transaction.

In other words, from the perspective of tire-2, tire-1 is also part of the past Transaction.

### fix

The proposed fix is to get the item of the lotID to be traced and get the material list of the config. Then, in the Output State of the Transaction, if the item is not included in the material list, exclude it.

This fix has no impact on the front-end.

![image](https://user-images.githubusercontent.com/38951987/118582280-08941300-b7ce-11eb-9e2a-7678b1af8467.png)

**Comment by davidleesbir3** [comment]
I see! So you assumed the outputs are only left-over states (rubber and wire in this case) ?

**Comment by KztTateyama** [comment]
Sorry. There was a crucial flaw in the above proposal.
For example, if you create a "car" using "tire-2" as the material for the next Transaction above, and then go back to it, you will still get "tire-1".

However, I have thought of another way.
The logic is very simple. That is, to recursively get the Product State that is the Input State of the Transaction.

The input State and output State are then compared to construct a tree hierarchy.

![image](https://user-images.githubusercontent.com/38951987/119770259-e77ea100-bef6-11eb-8fe1-a071ccdae1ff.png)
